version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 10
    reviewers:
      - onderceylan
    assignees:
      - onderceylan
    labels:
      - dep-upgrade
    versioning-strategy: widen
