name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install
        run: npm ci
      - name: audit signatures
        run: npm audit signatures
      # Building for the first time to make dep libs available for update
      - name: update prep
        run: npm run build
      - name: install chromium
        run: npm run chromium
      - name: update
        run: npm run update
        env:
          PAG_USE_LOCAL_REV: 1
          PAG_USE_NO_SANDBOX: 1
      - name: format
        run: npm run prettier:fix
      # Actual build with updated fallback data
      - name: build
        run: npm run build
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
